[package]
name = "futures-timer"
version = "0.3.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/futures-timer"
homepage = "https://github.com/alexcrichton/futures-timer"
documentation = "https://docs.rs/futures-timer"
description = """
Timeouts and intervals for futures.
"""

[dependencies]
futures-preview = "0.3.0-alpha.16"
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
runtime = "0.3.0-alpha.6"

[patch.crates-io.runtime]
git = "https://github.com/rustasync/runtime"
rev = "6177e6ead4f1a5fd23640db5d931d85b2dd55c5d"
